%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                           Function and Outputs
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
% This function creates images from the .mat files generated by PCA and
% uses the stdProjection (standard deviation projection) field of the
% structure to create a black and white representation of an entire movie.
% The output of this particular function is to create all of the .png
% files from the stdProjection field. It also calls a different function,
% sortandregister.m, to move each picture into a subdirectory (located in
% the same main folder) with the mouse name. These pictures are then
% registered and analyzed for transformation.
% Instructions: 
% Navigate to the folder containing all of the .mat files from PCA.
% Manually changed the path or use cd() to change the directory. 
% Next, run the script. Everything from then on should be automated.

%% Begin Function
clc
disp('Creating Images / Figures - Outputting to Current Directory')
disp('.')
disp('.')
disp('.')
% 
javaaddpath 'C:\Program Files\MATLAB\R2015a\java\jar\mij.jar'
javaaddpath 'C:\Program Files\MATLAB\R2015a\java\jar\ij.jar'
MIJ.start('C:\Users\Ashwin Chakicherla\Desktop\ImageJ')
d=dir('*.mat'); % <- retrieve all names: file(s) and folder(s)
d=d(~[d.isdir]); % <- keep file name(s), only
d={d.name}.'; % <- file name(s)
nf=numel(d);

%% Create the Images
for i=1:nf
    disp(sprintf('working on %5d/%5d: %s',i,nf,d{i}));
    filename = d{i};    
    load(filename); % Load the file
    figure
    imshow(PCAparams.stdProjection) % Create figure
    image(PCAparams.stdProjection)  % Create black and white figure   
    axis off;
    imagefile = strrep(filename,'.mat','');
    export_fig(imagefile,i); % Export and save the picture
end

close all
sortandregister;

